meshery-extensions/meshery-kuma

README.md
=> updated meshery-kuma README.md

kuma/install-kuma.go, kuma/kuma.go
@girishranganathan @leecalcote sir, may you check these changes and tell me are these changes are correct or not?
=> i changes some error of kuma repo

CONTRIBUTING.md
Signed-off-by: subhamkrai <subhamkumarrai03@gmail.com>
Fixes #11
=> #11 added CONTRIBUTUING.md

.github/workflows/ci.yml
I have made some change to solve the last 2 error.
fixes #20
=> updated ci_yml

README.md
Just added a few links to the README.md, close #24.
=> README.md: add links to badges

.github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/question.md
fixes #32 
Signed-off-by: ashiscs <ashissingh640@gmail.com>
=> added missing templates

.github/release-drafter.yml, .github/workflows/release-drafter.yml
Signed-off-by: Annysah <anisatakinbani13@gmail.com>
=> Set up release drafter

Dockerfile
=> fix: remove go mod vendor to not store irrelevant deps

go.sum, internal/config/defaults.go, internal/config/local.go, kuma/kuma.go, kuma/smi.go, kuma/spec.go, main.go, scripts/kuma/installer.sh
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
Simple change -> to maintain American English
=> chore: change adaptor to adapter

Dockerfile
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
=> chore: standardise go version in adapters

.github/workflows/ci.yml
Signed-off-by: kumarabd <abishekkumar92@gmail.com>
=> workflow updated

Dockerfile
Signed-off-by: kumarabd <abishekkumar92@gmail.com>
=> fixed mod issue in dockerfile

Dockerfile
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
fixes #108
=> fix: docker build failure in CI

Dockerfile
=> fix: docker image can't find utility scripts

.github/workflows/release-drafter.yml
@leecalcote After this, we can make a new release of kuma adapter with the script fixed
=> fix: use org-admin PAT insteam of gh-token

main.go
Signed-off-by: kumarabd <abishekkumar92@gmail.com>
=> fixes for kubeconfig

.github/workflows/ci.yml, kuma/error.go, kuma/kuma.go
- Added annotations to enable `sidecar-injections` for SMI test.
- Added comments for each error type
Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>
=> Enabled Sidecar injection

.github/workflows/ci.yml, .gitignore, README.md
Signed-off-by: aisuko <urakiny@gmail.com>
fiexes: #140 #141
=> Fix the CI configuration

go.mod, go.sum
Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>
This PR fixes: #146
=> Bump meshery-adapter-library to v0.1.13

kuma/install.go
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>
fixes : #155
=> Updated the address of Kuma Binaries

internal/config/error.go, kuma/error.go
Signed-off-by: dhruv0000 <patel.4@iitj.ac.in>
This PR updates the error descriptions for the errors defined.
=> Updated error description

internal/config/config.go
Signed-off-by: Shreyas220 <shreyas.ny@gmail.com>
SMP protos compliant operation name for kuma
=> SMP protos compliant operation name for kuma

.github/workflows/update-oam-defs.yml
Signed-off-by: Shreyas220 <shreyas.ny@gmail.com>
Updated the github workflow to generate the JSON schemas and Definitions for Kuma components
#174  
i no longer have access to #180, sorry for the inconvenience 
=> Updated the github workflow to generate the JSON schemas and Definitions for Kuma components

Dockerfile, go.mod, internal/config/config.go, kuma/error.go, kuma/kuma.go, kuma/oam.go, kuma/oam/doc.go, kuma/oam/parser.go, kuma/oam/register.go, kuma/sample_apps.go, main.go, templates/oam/traits/automaticsidecarinjection.kuma.meshery.layer5io.schema.json, templates/oam/traits/automaticsidecarinjection.kuma_definition.json, templates/oam/workloads/kumamesh.meshery.layer5io.schema.json, templates/oam/workloads/kumamesh_definition.json
Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>
Adding the Pattern support for the KUMA mesh.
This PR fixes #187 
=> Adding Pattern Support

.github/workflows/error-ref-publisher.yml, helpers/component_info.json, internal/config/error.go
Signed-off-by: Suryashankar Das <suryashankardas.2002@gmail.com>
Fix glob to match all required `error.go` files
Related to [this](https://github.com/meshery/meshery-istio/issues/267) issue
=> [CI] update file pattern glob

.github/workflows/build-and-release.yml, .github/workflows/ci.yml, Dockerfile
Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>**Description**
hello
=> [build] use a nodejs compatible container base image

kuma/error.go, kuma/sample_apps.go
Signed-off-by: Shreyas220 <shreyas.ny@gmail.com>
This PR fixes an instance of a misused meshkit logger
=> fix a misused meshkit logger

kuma/oam.go
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>
=> Fixed failing pattern due to wrong arguments

.github/install/deploy.yaml, .github/workflows/e2etest.yaml
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>
=> Added e2e test

.github/workflows/ci.yml
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>
=> Solved failing security check

Dockerfile
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>
Related to meshery/meshery#4642
Needs checks
=> Bump tags for CVE fix

.github/workflows/newcomers-alert.yml
Signed-off-by: Ankita Pareek <ankitapareek2000@gmail.com>
- This PR adds a workflow to notify about good first issues on the #newcomer channel of Layer5.
- The slack.yml file is already updated.
This PR fixes #219 
=> Add newcomers workflow to notify about good first issues on slack

kuma/error.go
Signed-off-by: asubedy <frexpe@pm.me>
=> Enhanced OAM error description

kuma/install.go
Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>
=> Fix failing helm install due to meshkit version update.

Dockerfile
Signed-off-by: Lee Calcote <lee.calcote@layer5.io>
This PR fixes security vulnerabilities.
=> [CI] Update docker image to node:latest-arm64

Makefile, build/Makefile.core.mk, build/Makefile.show-help.mk
Signed-off-by: leecalcote <leecalcote@gmail.com>
=> [CI] Normalize makefile

Dockerfile
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>
=> Remove AMD64 hardcoding and kubeopenapi

Dockerfile
Signed-off-by: Ruturaj Mohite <53974118+gr455@users.noreply.github.com>
=> Kuma: Remove arch hardcode and kubeopenapi-jsonschema

.github/workflows/multi-platform.yml
Signed-off-by: Hanish Rishen <hanishrishen@gmail.com>
This PR fixes #328 
=> Update multi-platform workflow with correct build args

go.mod, go.sum
Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>
=> [chore] Upgrade Meshkit

.github/workflows/e2etest.yaml
=> Update e2etest.yaml to reference v2 adapter workflow

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/ci.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Updating Figma Open Invite Link in Docs

.github/config.yml
=> replacing the dead link in GitHub workflow
